"""empty message

Revision ID: 343d775891df
Revises: 29c9c736147c
Create Date: 2025-12-22 15:24:10.795449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343d775891df'
down_revision = '29c9c736147c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('owner', sa.String(), nullable=False))

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('board_id')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('message')

    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.drop_column('owner')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
