"""empty message

Revision ID: a42753c1f04e
Revises: 343d775891df
Create Date: 2025-12-23 00:05:51.813273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42753c1f04e'
down_revision = '343d775891df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
